### ISSUE TITLE
这个没有处理验证码么

### ISSUE THREAD

**Issue by SilentTTxo** [xqin/PiWebQQ#1]
RT

**Comment by xqin** [comment]
程序执行后,所有的输出都在`qq.log`中, 
当发现需要验证码时, 程序所在目录里会出现一个`v.jpg`的文件,
就是所要输入的验证码的图片文件,
接下来需要在程序所在目录创建一个 `v.txt` 的文件,
内容为图片中的验证码字符, 可通过以下方式创建:

```
echo "abcd" > v.txt
```

# 

PS: 不会`Python`的同学,不建议使用本程序.
提`issue`之前不阅读代码的同学,也不建议使用本程序.

**Comment by SilentTTxo** [comment]
我看了log，也看了代码，当时就没看懂v.txt是什么，我以为你写了函数来处理v.jpg,不好意思麻烦了
